# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 04:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rides', models.IntegerField(default=0, null=True)),
                ('total_earned', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('date', models.DateTimeField()),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Suturday'), (6, 'Sunday')], default=0)),
                ('time_worked', models.DurationField(null=True)),
                ('rate_per_ride', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_user_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('trip_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15)),
                ('total_earned', models.DecimalField(decimal_places=2, max_digits=8)),
                ('surge', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateTimeField()),
                ('request_at', models.DateTimeField()),
                ('begintrip_at', models.DateTimeField(null=True)),
                ('dropoff_at', models.DateTimeField(null=True)),
                ('duration', models.DurationField()),
                ('day_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_app.DayStatement')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_app.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='WeekStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_at', models.DateTimeField(null=True, unique=True)),
                ('ending_at', models.DateTimeField(null=True, unique=True)),
                ('total_earned', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('trip_count', models.PositiveSmallIntegerField(null=True)),
                ('rate_per_ride', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('rate_per_day', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_rides', models.IntegerField(default=0, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_app.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='week_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_app.WeekStatement'),
        ),
        migrations.AddField(
            model_name='daystatement',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_app.Driver'),
        ),
        migrations.AddField(
            model_name='daystatement',
            name='week_statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver_app.WeekStatement'),
        ),
    ]
