# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_user_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('trip_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=15)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('uber_fee', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_earned', models.DecimalField(decimal_places=2, max_digits=8)),
                ('surge', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('currency_code', models.CharField(max_length=5)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateTimeField()),
                ('request_at', models.DateTimeField()),
                ('begintrip_at', models.DateTimeField()),
                ('dropoff_at', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('driver_feedback', models.PositiveSmallIntegerField()),
                ('driver_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ride_type', models.CharField(max_length=25)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_app.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('statement_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('starting_at', models.DateTimeField()),
                ('ending_at', models.DateTimeField()),
                ('total_earned', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_uber_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_surge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trip_count', models.PositiveSmallIntegerField()),
                ('total_distance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('city', models.SlugField(max_length=100)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_app.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_app.Statement'),
        ),
    ]
