# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rides', models.IntegerField(default=0)),
                ('total_earned', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField()),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Suturday'), (6, 'Sunday')], default=0)),
                ('time_worked', models.DurationField()),
                ('rate_per_ride', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RenameModel(
            old_name='Statement',
            new_name='WeekStatement',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='statement',
            new_name='week_statement',
        ),
        migrations.AddField(
            model_name='daystatement',
            name='week_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_app.WeekStatement'),
        ),
        migrations.AddField(
            model_name='ride',
            name='day_statement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='driver_app.DayStatement'),
            preserve_default=False,
        ),
    ]
