# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0002_auto_20160603_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_at', models.DateField()),
                ('ending_at', models.DateField()),
                ('total_earned', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('rate_per_ride', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('rate_per_day', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_rides', models.IntegerField(default=0, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_app.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='daystatement',
            name='month_statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver_app.MonthStatement'),
        ),
        migrations.AddField(
            model_name='ride',
            name='month_statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver_app.MonthStatement'),
        ),
        migrations.AddField(
            model_name='weekstatement',
            name='month_statement',
            field=models.ManyToManyField(null=True, to='driver_app.MonthStatement'),
        ),
    ]
