# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0002_auto_20160603_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekstatement',
            name='ending_at',
            field=models.DateField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='weekstatement',
            name='starting_at',
            field=models.DateField(null=True, unique=True),
        ),
    ]
