# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0003_auto_20160603_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekstatement',
            name='trip_count',
        ),
    ]
