# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0003_auto_20160603_1849'),
        ('driver_app', '0002_auto_20160603_1507'),
    ]

    operations = [
    ]
