# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='day_statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver_app.DayStatement'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='week_statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='driver_app.WeekStatement'),
        ),
    ]
