# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0005_auto_20160605_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='surge',
        ),
        migrations.AddField(
            model_name='monthstatement',
            name='month_name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
