# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0006_auto_20160606_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekstatement',
            name='month_statement',
            field=models.ManyToManyField(to='driver_app.MonthStatement'),
        ),
    ]
